### ISSUE TITLE
在 Releases 中是否可以提供一个包含许可证在内的 zip 包

### ISSUE THREAD

**Issue by TakWolf** [ItMarki/MisekiBitmap#1]
RT. 以保证分发的完整性，而不需要单独下载许可证。谢谢。

请问有两个问题：

1. Mincho 和无印版的区别是什么？ 无印是黑体风格，而 Mincho 是宋体风格吗？
2. 字形写法是以港台字形为基准吗？还是以简体为基准？

**Comment by TakWolf** [comment]
![image](https://github.com/ItMarki/MisekiBitmap/assets/6064962/9e24153a-1132-40d6-9520-8d4caa91536f)
<img width="402" alt="image" src="https://github.com/ItMarki/MisekiBitmap/assets/6064962/28439f0a-abe5-4f8a-a89d-769c4922e5b2">

两个都存在笔画装饰

**Comment by ItMarki** [comment]
1. 可以，我之后做。
2. 明朝版和无印版的差别只在于假名和注音符号的风格。
3. 字体采用中国大陆字形标准。
4. 这些装饰是美咲字体本来就有的特征。

**Comment by ItMarki** [comment]
第1点在v1.12.1中解决了。
