### ISSUE TITLE
位图层 EBDT 字符映射错乱

### ISSUE THREAD

**Issue by TakWolf** [ItMarki/MisekiBitmap#3]
示例：

```python
if __name__ == '__main__':
    font = ImageFont.truetype(path_define.fonts_dir.joinpath('miseki-bitmap', 'MisekiBitmap.ttf'), 8)
    image = Image.new('RGBA', (100, 100), (255, 255, 255, 255))
    ImageDraw.Draw(image).text((10, 10), '你好中国！', fill=(0, 0, 0, 255), font=font)
    path_define.outputs_dir.mkdir(parents=True, exist_ok=True)
    image.save(path_define.outputs_dir.joinpath('test.png'))
```

结果：

![test](https://github.com/ItMarki/MisekiBitmap/assets/6064962/ac742180-962e-4818-8cdf-22d5cab70909)

<img width="330" alt="image" src="https://github.com/ItMarki/MisekiBitmap/assets/6064962/b978fed6-f7f5-4d7b-9f56-d50923dcb0a9">

输出和结果明显对不上

 MisekiBitmap 使用了 EBDT 表，看起来似乎是字体的问题

**Comment by TakWolf** [comment]
font_size 不设置为 8px 时（让字体尺寸不与 EBDT 设置的 8px 匹配），渲染正确：

例如：16px
```python
if __name__ == '__main__':
    font = ImageFont.truetype(path_define.fonts_dir.joinpath('miseki-bitmap', 'MisekiBitmap.ttf'), 16)
    image = Image.new('RGBA', (100, 100), (255, 255, 255, 255))
    ImageDraw.Draw(image).text((10, 10), '你好中国！', fill=(0, 0, 0, 255), font=font)
    path_define.outputs_dir.mkdir(parents=True, exist_ok=True)
    image.save(path_define.outputs_dir.joinpath('test.png'))
```

<img width="457" alt="image" src="https://github.com/ItMarki/MisekiBitmap/assets/6064962/16695614-b0df-43bc-8f15-98ded51b6eb8">

设置为 10px:

```python
if __name__ == '__main__':
    font = ImageFont.truetype(path_define.fonts_dir.joinpath('miseki-bitmap', 'MisekiBitmap.ttf'), 10)
    image = Image.new('RGBA', (100, 100), (255, 255, 255, 255))
    ImageDraw.Draw(image).text((10, 10), '你好中国！', fill=(0, 0, 0, 255), font=font)
    path_define.outputs_dir.mkdir(parents=True, exist_ok=True)
    image.save(path_define.outputs_dir.joinpath('test.png'))
```

<img width="625" alt="image" src="https://github.com/ItMarki/MisekiBitmap/assets/6064962/d39632a9-79e2-4419-ab29-d90b40ae1bfd">

看起来 EBDT 中字形映射是错乱的

**Comment by TakWolf** [comment]
使用 FontForge 预览 8px bitmap ，映射完全不对。

<img width="1291" alt="image" src="https://github.com/ItMarki/MisekiBitmap/assets/6064962/df106397-bb88-4dd7-8358-f096e4714f7e">

**Comment by ItMarki** [comment]
已删除文件。
